In [1]:
import numpy as np 
import rospy 
import os 
import sys
sys.path.append("..")
from kinematics.class_structure import CHAIN

print("Done.")

Done.


### Chain: UR5 OnRobot

In [2]:
file_name = "../urdf/ur5/ur5_onrobot.urdf"
chain = CHAIN(file_name=file_name, base_offset=[0,0,0], verbose=False)
chain.add_joi_to_robot()
chain.add_link_to_robot()
chain.fk_chain(1)
print(chain.joint[7].name ,chain.joint[7].p)

ee_fixed_joint [[ 0.81725 ]
 [ 0.19145 ]
 [-0.005491]]


### Chain: UR5e 

In [3]:
file_name = "../urdf/ur5e/ur5e.urdf"
chain = CHAIN(file_name=file_name, base_offset=[0,0,0], verbose=True)
chain.add_joi_to_robot()

Name: base_joint                         , ID: 1 , Mother_joint: 0 , Child_joint: [2, 15]    , Type: fixed     , Axis: [[0. 0. 1.]]    , B_offset:[[0. 0. 0.]]
Current Position: [[0 0 0]]
Current Rotation: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Name: shoulder_pan_joint                 , ID: 2 , Mother_joint: 1 , Child_joint: [3]        , Type: revolute  , Axis: [[0. 0. 1.]]    , B_offset:[[0.    0.    0.163]]
Current Position: [[0 0 0]]
Current Rotation: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Name: shoulder_lift_joint                , ID: 3 , Mother_joint: 2 , Child_joint: [4]        , Type: revolute  , Axis: [[0. 1. 0.]]    , B_offset:[[0.    0.138 0.   ]]
Current Position: [[0 0 0]]
Current Rotation: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Name: elbow_joint                        , ID: 4 , Mother_joint: 3 , Child_joint: [5]        , Type: revolute  , Axis: [[0. 1. 0.]]    , B_offset:[[ 0.    -0.131  0.425]]
Current Position: [[0 0 0]]
Current Rotation: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 

### Chain: Panda 

In [4]:
file_name = "../urdf/panda/panda.urdf"
chain = CHAIN(file_name=file_name, base_offset=[0,0,0], verbose=False)
chain.add_joi_to_robot()
chain.add_joi_to_robot()
chain.add_link_to_robot()
chain.fk_chain(1)
print(chain.joint[10].name ,chain.joint[10].p)

panda_eef_fixed [[ 8.80000000e-02]
 [-1.65994362e-12]
 [ 8.29500000e-01]]
